GET http://localhost:3000

###
GET http://localhost:3000/api/customer

###
GET http://localhost:3000/api/customer/63b4fb20a945da14db550282
###
POST http://localhost:3000/api/customer HTTP/1.1
Content-Type: application/json

{
    "CustomerId": 1004,
    "FullName": "Mahiru",
    "Address":  "Japan"
}
###
PUT http://localhost:3000/api/customer/63b4fb20a945da14db550282 HTTP/1.1
Content-Type: application/json

{
    "CustomerId": 1003,
    "FullName": "Bank",
    "Address": "Pathumthani"
}
###
DELETE  http://localhost:3000/api/customer/63b5075a71a622293b0587b6 HTTP/1.1